### PR TITLE
Added commands to create a database and container in the create_database script

### PR DESCRIPTION
**Pull request by juliamuiruri4**
Description: The CREATE_DATABASE.sh script does not automatically create the database and container.
Updated from:
image

To:
image

Output:
image

### CODE REVIEW

**Comment by juliamuiruri4** [comment]
@glaucia86 - Please have a look at this. Thanks

**Comment by glaucia86** [comment]
> @glaucia86 - Please have a look at this. Thanks

I will take a look today. Thanks, @juliamuiruri4

**Review by glaucia86 — APPROVED** [review]
LGTM!

@diberry any additional comment about it?

**Comment by diberry** [comment]
@juliamuiruri4 Thank you for the additional comments and the correct/complete script. I also appreciate the screenshot in the PR. 

LGTM

**Pull request merged**
